title: Andrea Biaggi
logo: /assets/img/logo.jpg
description: Computer Scientist
theme: jekyll-theme-slate
github:
  repository_url: https://github.com/AndreJackBia/AndreJackBia.github.io
  another_url: https://github.com/AndreJackBia
